# Generated by Django 3.2 on 2021-04-22 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(default='john smith', max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='urgency',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
